name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_KEY }}
          aws-secret-access-key: ${{ secrets.ACCES_KEY }}
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://mini-lab-cicd-tonnom --delete --exclude ".git/*" --exclude ".github/*"
      - name: Deploy app on EC2 via SSM
        env:
          INSTANCE_ID: i-0c1e4b421908fdedd
          BUCKET_NAME: mini-lab-cicd-tonnom
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy app from S3" \
            --parameters 'commands=[
              "aws s3 cp s3://'$BUCKET_NAME'/app.zip /tmp/app.zip",
              "unzip -o /tmp/app.zip -d /opt/app",
              "bash /opt/app/start.sh"
            ]' \
            --region eu-north-1
